/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppDesempenhoRouteImport } from './routes/app.desempenho'
import { Route as AppEstudarRouteImport } from './routes/app.estudar'
import { Route as AppFaculdadeRouteImport } from './routes/app.faculdade'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppPlanejamentoRouteImport } from './routes/app.planejamento'
import { Route as AppQuestoesRouteImport } from './routes/app.questoes'
import { Route as AppEstudosIndexRouteImport } from './routes/app.estudos.index'
import { Route as AppEstudosAreaIdIndexRouteImport } from './routes/app.estudos.$areaId.index'
import { Route as AppEstudosAreaIdCursosCourseIdRouteImport } from './routes/app.estudos.$areaId.cursos.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDesempenhoRoute = AppDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudarRoute = AppEstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => AppRoute,
} as any)
const AppFaculdadeRoute = AppFaculdadeRouteImport.update({
  id: '/faculdade',
  path: '/faculdade',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestoesRoute = AppQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosIndexRoute = AppEstudosIndexRouteImport.update({
  id: '/estudos/',
  path: '/estudos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosAreaIdIndexRoute = AppEstudosAreaIdIndexRouteImport.update({
  id: '/estudos/$areaId/',
  path: '/estudos/$areaId/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosAreaIdCursosCourseIdRoute =
  AppEstudosAreaIdCursosCourseIdRouteImport.update({
    id: '/estudos/$areaId/cursos/$courseId',
    path: '/estudos/$areaId/cursos/$courseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/faculdade': typeof AppFaculdadeRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app/': typeof AppIndexRoute
  '/app/estudos/': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId/': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId': typeof AppEstudosAreaIdCursosCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/faculdade': typeof AppFaculdadeRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app': typeof AppIndexRoute
  '/app/estudos': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId': typeof AppEstudosAreaIdCursosCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/faculdade': typeof AppFaculdadeRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app/': typeof AppIndexRoute
  '/app/estudos/': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId/': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId': typeof AppEstudosAreaIdCursosCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/faculdade'
    | '/app/flashcards'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app/'
    | '/app/estudos/'
    | '/app/estudos/$areaId/'
    | '/app/estudos/$areaId/cursos/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/faculdade'
    | '/app/flashcards'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app'
    | '/app/estudos'
    | '/app/estudos/$areaId'
    | '/app/estudos/$areaId/cursos/$courseId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/faculdade'
    | '/app/flashcards'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app/'
    | '/app/estudos/'
    | '/app/estudos/$areaId/'
    | '/app/estudos/$areaId/cursos/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desempenho': {
      id: '/app/desempenho'
      path: '/desempenho'
      fullPath: '/app/desempenho'
      preLoaderRoute: typeof AppDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudar': {
      id: '/app/estudar'
      path: '/estudar'
      fullPath: '/app/estudar'
      preLoaderRoute: typeof AppEstudarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faculdade': {
      id: '/app/faculdade'
      path: '/faculdade'
      fullPath: '/app/faculdade'
      preLoaderRoute: typeof AppFaculdadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planejamento': {
      id: '/app/planejamento'
      path: '/planejamento'
      fullPath: '/app/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questoes': {
      id: '/app/questoes'
      path: '/questoes'
      fullPath: '/app/questoes'
      preLoaderRoute: typeof AppQuestoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/': {
      id: '/app/estudos/'
      path: '/estudos'
      fullPath: '/app/estudos/'
      preLoaderRoute: typeof AppEstudosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/': {
      id: '/app/estudos/$areaId/'
      path: '/estudos/$areaId'
      fullPath: '/app/estudos/$areaId/'
      preLoaderRoute: typeof AppEstudosAreaIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/cursos/$courseId': {
      id: '/app/estudos/$areaId/cursos/$courseId'
      path: '/estudos/$areaId/cursos/$courseId'
      fullPath: '/app/estudos/$areaId/cursos/$courseId'
      preLoaderRoute: typeof AppEstudosAreaIdCursosCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDesempenhoRoute: typeof AppDesempenhoRoute
  AppEstudarRoute: typeof AppEstudarRoute
  AppFaculdadeRoute: typeof AppFaculdadeRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppQuestoesRoute: typeof AppQuestoesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEstudosIndexRoute: typeof AppEstudosIndexRoute
  AppEstudosAreaIdIndexRoute: typeof AppEstudosAreaIdIndexRoute
  AppEstudosAreaIdCursosCourseIdRoute: typeof AppEstudosAreaIdCursosCourseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDesempenhoRoute: AppDesempenhoRoute,
  AppEstudarRoute: AppEstudarRoute,
  AppFaculdadeRoute: AppFaculdadeRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppQuestoesRoute: AppQuestoesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEstudosIndexRoute: AppEstudosIndexRoute,
  AppEstudosAreaIdIndexRoute: AppEstudosAreaIdIndexRoute,
  AppEstudosAreaIdCursosCourseIdRoute: AppEstudosAreaIdCursosCourseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
