/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPlanejamentoRouteImport } from './routes/app.planejamento'
import { Route as AppEstudarRouteImport } from './routes/app.estudar'
import { Route as AppDesempenhoRouteImport } from './routes/app.desempenho'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as AppEstudosIndexRouteImport } from './routes/app.estudos.index'
import { Route as AppLabEditorRouteImport } from './routes/app.lab.editor'
import { Route as AppEstudosAreaIdIndexRouteImport } from './routes/app.estudos.$areaId.index'
import { Route as AppEstudosAreaIdCursosCourseIdIndexRouteImport } from './routes/app.estudos.$areaId.cursos.$courseId.index'
import { Route as AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRouteImport } from './routes/app.estudos.$areaId.cursos.$courseId.modulos.$moduleId.index'
import { Route as AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRouteImport } from './routes/app.estudos.$areaId.cursos.$courseId.modulos.$moduleId.aulas.$lessonId'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudarRoute = AppEstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => AppRoute,
} as any)
const AppDesempenhoRoute = AppDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosIndexRoute = AppEstudosIndexRouteImport.update({
  id: '/estudos/',
  path: '/estudos/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabEditorRoute = AppLabEditorRouteImport.update({
  id: '/lab/editor',
  path: '/lab/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosAreaIdIndexRoute = AppEstudosAreaIdIndexRouteImport.update({
  id: '/estudos/$areaId/',
  path: '/estudos/$areaId/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosAreaIdCursosCourseIdIndexRoute =
  AppEstudosAreaIdCursosCourseIdIndexRouteImport.update({
    id: '/estudos/$areaId/cursos/$courseId/',
    path: '/estudos/$areaId/cursos/$courseId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute =
  AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRouteImport.update({
    id: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId/',
    path: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute =
  AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRouteImport.update({
    id: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId',
    path: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/': typeof AppIndexRoute
  '/app/lab/editor': typeof AppLabEditorRoute
  '/app/estudos/': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId/': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/': typeof AppEstudosAreaIdCursosCourseIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app': typeof AppIndexRoute
  '/app/lab/editor': typeof AppLabEditorRoute
  '/app/estudos': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId': typeof AppEstudosAreaIdCursosCourseIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/estudar': typeof AppEstudarRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/': typeof AppIndexRoute
  '/app/lab/editor': typeof AppLabEditorRoute
  '/app/estudos/': typeof AppEstudosIndexRoute
  '/app/estudos/$areaId/': typeof AppEstudosAreaIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/': typeof AppEstudosAreaIdCursosCourseIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute
  '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId': typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/planejamento'
    | '/app/'
    | '/app/lab/editor'
    | '/app/estudos/'
    | '/app/estudos/$areaId/'
    | '/app/estudos/$areaId/cursos/$courseId/'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/planejamento'
    | '/app'
    | '/app/lab/editor'
    | '/app/estudos'
    | '/app/estudos/$areaId'
    | '/app/estudos/$areaId/cursos/$courseId'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/estudar'
    | '/app/planejamento'
    | '/app/'
    | '/app/lab/editor'
    | '/app/estudos/'
    | '/app/estudos/$areaId/'
    | '/app/estudos/$areaId/cursos/$courseId/'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/'
    | '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planejamento': {
      id: '/app/planejamento'
      path: '/planejamento'
      fullPath: '/app/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudar': {
      id: '/app/estudar'
      path: '/estudar'
      fullPath: '/app/estudar'
      preLoaderRoute: typeof AppEstudarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desempenho': {
      id: '/app/desempenho'
      path: '/desempenho'
      fullPath: '/app/desempenho'
      preLoaderRoute: typeof AppDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/': {
      id: '/app/estudos/'
      path: '/estudos'
      fullPath: '/app/estudos/'
      preLoaderRoute: typeof AppEstudosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/editor': {
      id: '/app/lab/editor'
      path: '/lab/editor'
      fullPath: '/app/lab/editor'
      preLoaderRoute: typeof AppLabEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/': {
      id: '/app/estudos/$areaId/'
      path: '/estudos/$areaId'
      fullPath: '/app/estudos/$areaId/'
      preLoaderRoute: typeof AppEstudosAreaIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/cursos/$courseId/': {
      id: '/app/estudos/$areaId/cursos/$courseId/'
      path: '/estudos/$areaId/cursos/$courseId'
      fullPath: '/app/estudos/$areaId/cursos/$courseId/'
      preLoaderRoute: typeof AppEstudosAreaIdCursosCourseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/': {
      id: '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/'
      path: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId'
      fullPath: '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/'
      preLoaderRoute: typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId': {
      id: '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
      path: '/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
      fullPath: '/app/estudos/$areaId/cursos/$courseId/modulos/$moduleId/aulas/$lessonId'
      preLoaderRoute: typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDesempenhoRoute: typeof AppDesempenhoRoute
  AppEstudarRoute: typeof AppEstudarRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLabEditorRoute: typeof AppLabEditorRoute
  AppEstudosIndexRoute: typeof AppEstudosIndexRoute
  AppEstudosAreaIdIndexRoute: typeof AppEstudosAreaIdIndexRoute
  AppEstudosAreaIdCursosCourseIdIndexRoute: typeof AppEstudosAreaIdCursosCourseIdIndexRoute
  AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute: typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute
  AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute: typeof AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDesempenhoRoute: AppDesempenhoRoute,
  AppEstudarRoute: AppEstudarRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppIndexRoute: AppIndexRoute,
  AppLabEditorRoute: AppLabEditorRoute,
  AppEstudosIndexRoute: AppEstudosIndexRoute,
  AppEstudosAreaIdIndexRoute: AppEstudosAreaIdIndexRoute,
  AppEstudosAreaIdCursosCourseIdIndexRoute:
    AppEstudosAreaIdCursosCourseIdIndexRoute,
  AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute:
    AppEstudosAreaIdCursosCourseIdModulosModuleIdIndexRoute,
  AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute:
    AppEstudosAreaIdCursosCourseIdModulosModuleIdAulasLessonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
